// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Entities;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230103203418_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProjectRecommendId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRecommendId")
                        .IsUnique()
                        .HasFilter("[ProjectRecommendId] IS NOT NULL");

                    b.ToTable("Ogrenciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 3, 23, 34, 17, 931, DateTimeKind.Local).AddTicks(6596),
                            FullName = "Hasan",
                            Password = "11111111",
                            Role = "admin",
                            StudentName = "hasan"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 3, 23, 34, 17, 931, DateTimeKind.Local).AddTicks(6599),
                            FullName = "mevlut",
                            Password = "11111111",
                            Role = "user",
                            StudentName = "mevlut"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 3, 23, 34, 17, 931, DateTimeKind.Local).AddTicks(6602),
                            FullName = "ibrahim",
                            Password = "11111111",
                            Role = "user",
                            StudentName = "ibrahim"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.ProjectRecommendEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnahtarKelimeler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OgretmenOnayDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("Ozet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SimilarityOnayDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("SimilarityScore")
                        .HasColumnType("int");

                    b.Property<string>("TeacherComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectRecommendEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnahtarKelimeler = "Nanokristal teknolojisi, Suda çözünür ilaçlar, Oral yol, Hazırlama yöntemleri",
                            Baslik = "İLAÇLARIN ETKEN MADDESİNİN KONTROLLÜ ELDESİ VE İYİLEŞTİRİCİ ETKİLERİNİN ARTTIRILMASI ÜZERİNE YENİ BİR YÖNTEM",
                            OgrenciId = 2,
                            OgrenciName = "mevlut",
                            OgretmenOnayDurumu = true,
                            Ozet = "Nanokristal teknolojisi partikül boyutu 1000 nanometre (nm)’nin altında,herhangi bir taşıyıcı sisteme ihtiyaç duymadan katı ilaç partikülerinin üretilmesini sağlar. Sudaki çözünürlüğü düşük ilaçların partiküllerinin boyutunun küçültülmesi ile, yüzey alanlarının artması ve difüzyon tabakasının kalınlığının azaltılması k çözünürlük hızının da artışına yol açar. Buna bağlı olarak, absorpsiyon bölgesinde artan konsantrasyon gradienti bağırsak lümeni v kan arasındaki pasif difüzyon yoluyla permeasyonu ve emilimi teşvik etmektedir. Dolayısıyla Biyofarmasötik Sınıflandırma Sistemi (BCS) Sınıf II ve IV’e ait ilaç molekülleri için nanokristal teknolojisi yaklaşımını kullanarak biyoyararlanımlarını geliştirmek ve/veya arttırmak oldukça önemlidir. Nanometren boyutunda ilaç partikülü elde edebilmek için yukarıdan aşağıya (top-down) ve aşağıdan yukarıya (bottom-up) yöntemlerinden yararlanılmaktadır. İlaç endüstrisinde uygulama kolaylığı, tekrar edilebilirliği ve ölçeklendirilebilmesinedeniyle bilyeli değirmende yaş öğütme (BWM) ve yüksek basınçlı homojenizasyon (HPH) olarak alt bölümlere ayrılan yukarıdan aşağıya yöntemleri tercih edilmektedir. Nanokristal teknolojisi ile ilaç endüstrisinde hâlihazırda tedavide onaylanmış olan ilaç moleküllerinin daha az yan etki, daha düşük dozlar ve daha hızlı etki başlangıcı sağlayarak yeni dozaj formlarının geliştirilmesi ve yeni ilaç moleküllerinin daha iyi bir biyoyararlanımla formüle edilebilmesi amaçlanmaktadır.",
                            SimilarityOnayDurumu = true,
                            SimilarityScore = 45,
                            TeacherComment = "",
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 2,
                            AnahtarKelimeler = "Bakteriyel selüloz, Acetobacter, Ekzopolisakkarit, Fermantasyon",
                            Baslik = "Bakteriyel Selülozların Üretimi ve Özellikleri ile Gıda ve Gıda Dışı Uygulamalarda Kullanımı",
                            OgrenciId = 3,
                            OgrenciName = "ibrahim",
                            OgretmenOnayDurumu = true,
                            Ozet = "Selüloz D-glukopiranoz birimlerinin β-1,4 glikozidik bağlarla bağlanmasıyla oluşan lineer ve dünyada en yaygın olarak bulunan polimerdir. Selüloz, bitkilerin yanında bazı bakteriler tarafından da üretilmektedir. Bakteriyel selüloz olarakadlandırılan bu tip selülozlar gıda, ilaç, biyoteknoloji, biyomedikal, kozmetik, kağıt ve elektronik alanlarında kullanımı giderek artmaktadır. Saf olarak elde edilmesi, elastik, ağsı yapıda, yüksek kristalizasyon derecesi, yüzey alanı, su tutma kapasitesine ve gerilme direncine, daha ince ve gözenekli bir yapıya sahip olması gibi bitkisel selüloza kıyasla pek çok üstün özellikleri bulunmaktadır. Bu derleme bakteriyel selülozun üretimini, üretiminde kullanılan yöntemleri, nüretilen polimerin özelliklerini ve gıda ve gıda dışı uygulamalarda kullanımını kapsamaktadır.",
                            SimilarityOnayDurumu = true,
                            SimilarityScore = 50,
                            TeacherComment = "",
                            Yil = "2022"
                        },
                        new
                        {
                            Id = 3,
                            AnahtarKelimeler = "Tavuk, kanatlı kırmızı akarı, sentetik akarisitler, bitkisel ürünler",
                            Baslik = "Yumurta Tavukçuluğunda Kanatlı Kırmızı Akarı (Dermanyssus gallinae) Problemi ve Mücadele",
                            OgrenciId = 2,
                            OgrenciName = "mevlut",
                            OgretmenOnayDurumu = true,
                            Ozet = "Kanatlı kırmızı akarı (Dermanyssus gallinae) dünyanın birçok ülkesinde yumurta tavukçuluğu endüstrisine büyük ekonomik zararlar veren bir dış parazittir. Kan ile beslenen bu parazit tavuğun sağlığını, refahını ve verim performansını olumsuz etkiler. Kanatlı kırmızı akarı ile mücadelede en popüler metot çeşitli sentetik akarisitlerin kullanılmasıdır. Ancak, kimyasal uygulamalar, akar direnci, aktif bileşenlerin etkisizliği ve ürünlerde ve çevrede zararlı artıklar gibi çok sayıda soruna yol açabilmektedir. Bu nedenle, kanatlı kırmızı akarı ile mücadelede çevreye ve insan sağlığına daha az zarar verebilecek yeni alternatif kaynakların belirlenmesi giderek önem kazanmaktadır. Organik gıda üretiminde kullanılan bitkisel ürünler kimyasal akarisitlere alternatif olabilir. Bu derlemede, kanatlı kırmızı akarların özellikleri, sentetik akarisitlerin neden olduğu sorunlar ve bitkisel ürünlerin akarisitler olarak kullanım potansiyelleri irdelenmiştir.",
                            SimilarityOnayDurumu = true,
                            SimilarityScore = 41,
                            TeacherComment = "",
                            Yil = "2022"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Ogrenci", b =>
                {
                    b.HasOne("WebApplication1.Entities.ProjectRecommendEntity", "ProjectRecommend")
                        .WithOne("Ogrenci")
                        .HasForeignKey("WebApplication1.Entities.Ogrenci", "ProjectRecommendId");

                    b.Navigation("ProjectRecommend");
                });

            modelBuilder.Entity("WebApplication1.Entities.ProjectRecommendEntity", b =>
                {
                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
